collision_monitor:
  ros__parameters:
    enabled: True
    use_sim_time: True
    frequency: 20.0
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    
    cmd_vel_in_topic: "cmd_vel_raw"   # 맵핑/조종 노드에서 나오는 토픽
    cmd_vel_out_topic: "cmd_vel"     # 실제 모터로 나가는 토픽
    transform_tolerance: 0.5
    
    cmd_vel_timeout: 0.5 # 조종기 입력이 없어도 0.5초 동안은 마지막 명령을 바탕으로 안전을 계산함
    source_timeout: 5.0 # 센서 데이터가 5초 동안 안 들어오면 위험하다고 판단하고 로봇을 멈춤
    stop_pub_timeout: 1.0
    base_shift_correction: True # 로봇이 빠르게 움직일 때, 센서 데이터가 들어오는 찰나의 시간 차이만큼 로봇의 위치 변화를 보정
  
    # 사용할 원형 구역 이름 두 개 등록
    polygons: ["CircleStop", "CircleSlow"]

    # 1. 아주 가까울 때 (정지)
    CircleStop:
      type: "circle"
      radius: 0.5        # 로봇 중심에서 50cm 이내면 정지 (로봇 반지름보다 조금 크게)
      action_type: "stop"
      min_points: 3
      visualize: True
      polygon_pub_topic: "circle_stop"
      enabled: True

    # 2. 조금 거리가 있을 때 (감속)
    CircleSlow:
      type: "circle"
      radius: 1.5         # 로봇 중심에서 100cm 이내면 감속 시작
      action_type: "slowdown"
      slowdown_ratio: 0.2 # 원래 속도의 30%로 제한 (넘어짐 방지 핵심!)
      min_points: 3
      visualize: True
      polygon_pub_topic: "circle_slowdown"
      enabled: True

    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      enabled: True