collision_monitor:
  ros__parameters:
    enabled: True
    use_sim_time: True
    frequency: 20.0

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"

    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel"

    transform_tolerance: 0.5
    cmd_vel_timeout: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 0.2
    base_shift_correction: True

    polygons: ["CircleSlow"]

    CircleSlow:
      type: "circle"
      radius: 1.2
      action_type: "slowdown"
      slowdown_ratio: 0.05   # 거의 멈춤 수준 (넘어지지 않음)
      min_points: 3
      visualize: True
      polygon_pub_topic: "circle_slowdown"
      enabled: True

    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      enabled: True
