control_node:
  ros__parameters:
    auto_patrol: false
    operation_end: 08:30
    operation_start: '22:00'
homepoint:
- - 0.0
  - -3.5
waypoints:
- - 5.5
  - 0.0
- - 0.0
  - 7.0
- - 0.0
  - 0.0
- - -3.0
  - -3.0
